name: CI/CD Pipeline - Direct EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: docker build -t backend-app .

      - name: Save Docker Image
        run: docker save backend-app -o backend-app.tar

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend-app.tar"
          target: "/home/ubuntu/backend-app.tar"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i backend-app.tar
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 80:3000 \
              --env-file /home/ubuntu/.env backend-app

