name: CI/CD Pipeline - Node.js Backend (No Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu # or ec2-user depending on AMI
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app || mkdir -p /home/ubuntu/app && cd /home/ubuntu/app

            # Get latest code from GitHub
            if [ -d ".git" ]; then
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/AdityaPatil0708/sneaker-store-backend.git .
              git checkout main
            fi

            # Install dependencies
            npm install --production

            # Restart app with PM2
            pm2 stop backend || true
            pm2 delete backend || true
            pm2 start server.js --name backend
            pm2 save
